### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 1669083458** [suahnkim/skewed_histogram_shifting#1]
Hello. I'm sorry to bother you.
What is the purpose of this order? （ if loc_y > floor(log2(n*m))+2）

**Comment by suahnkim** [comment]
Sorry for the late reply, 
that part of the code makes sure that the embedding does not happen on the edge pixels. It is an optimized code for when pixels are ordered in linear index. 

usually pixels are stored in (x,y) coordinate -> to optimize, i store the pixels using linear indexing. You can search more about it on matlab. (how linear indexing work)
